### PR TITLE
Fix blocking HA process using asyncio

### LINKED ISSUE #8: Blocks the all processes for 3 seconds every 10 if the vacuum is offline
This was driving me nuts.
After enabling `debugpy:` and hacking the maximum log text length, I got this every 10 seconds.

``` 
2024-03-11 22:17:22.884 WARNING (MainThread) [asyncio] Executing <TimerHandle when=272320.416692397 _run_async_call_action(<HomeAssistant RUNNING>, <Job EntityPlatform poll media_player.sox: track time interval 10.0 <bound method EntityPlatform._async_handle_interval_callback of <EntityPlatform domain=media_player platform_name=sox config_entry=None>> HassJobType.Callback <bound method _TrackTimeInterval._interval_listener of _TrackTimeInterval(hass=<HomeAssistant RUNNING>, seconds=10.0, job_name='EntityPlatform poll media_player.sox: track time interval 10.0 <bound method EntityPlatform._async_handle_interval_callback of <EntityPlatform domain=media_player platform_name=sox config_entry=None>>', action=<bound method EntityPlatform._async_handle_interval_callback of <EntityPlatform domain=media_player platform_name=sox config_entry=None>>, cancel_on_shutdown=None, _track_job=<Job EntityPlatform poll media_player.sox: track time interval 10.0 <bound method EntityPlatform._async_handle_interval_callback of <EntityPlatform domain=media_player platform_name=sox config_entry=None>> HassJobType.Callback <bound method _TrackTimeInterval._interval_listener of ...>>, _run_job=<Job track time interval 10.0 HassJobType.Callback <bound method EntityPlatform._async_handle_interval_callback of <EntityPlatform domain=media_player platform_name=sox config_entry=None>>>, _cancel_callback=<bound method TimerHandle.cancel of <TimerHandle when=272330.417061447 _run_async_call_action(<HomeAssistant RUNNING>, <Job EntityPlatform poll media_player.sox: track time interval 10.0 <bound method EntityPlatform._async_handle_interval_callback of <EntityPlatform domain=media_player platform_name=sox config_entry=None>> HassJobType.Callback <bound method _TrackTimeInterval._interval_listener of ...>>) at /usr/src/homeassistant/homeassistant/helpers/event.py:1506 created at /usr/src/homeassistant/homeassistant/helpers/event.py:1530>>)>>) at /usr/src/homeassistant/homeassistant/helpers/event.py:1506 created at /usr/src/homeassistant/homeassistant/helpers/event.py:1530> took 3.065 seconds
```

I think the problem is that this integration uses socket instead of asyncio streams, and should therefore wrap the _send method with `hass.async_add_executor_job` so it doesn't block the event loop.

This would be good even if the vacuum cleaner is online, but it is particularly bad when offline as the socket has to wait for a timeout before letting the event loop thread go on.

### PR DESCRIPTION
**Pull request by dbuezas**
Also stop/play media on volume change so it is applied

Fixes #8

### CODE REVIEW

**Comment by definitio** [comment]
Thanks for contributing! There is unhandled exception when device is unavailable:
```python
2024-03-16 17:06:37.084 ERROR (MainThread) [homeassistant.helpers.entity] Update for media_player.vacuum fails
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 945, in async_update_ha_state
await self.async_device_update()
File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1262, in async_device_update
await self.async_update()
File "/config/custom_components/sox/media_player.py", line 218, in async_update
await self._async_send("") # For compatibility with old sound server
^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/config/custom_components/sox/media_player.py", line 195, in _async_send
if writer:
^^^^^^
UnboundLocalError: cannot access local variable 'writer' where it is not associated with a value
```

**Comment by dbuezas** [comment]
Ups missed that :)

**Comment by definitio** [comment]
Integration doesn't try to connect to device if it was offline during HA start. However after successful start reconnecting works. Any ideas?

**Comment by dbuezas** [comment]
I'm suspecting of `self._is_connected is None` in:
```py
async def async_update(self):
        """Get the latest data and update the state."""
        if self._is_connected is None or self._volume is not None:
            await self._async_send("")  # For compatibility with old sound server
```

Although it should connect as soon as a command is sent. I'm testing that.

BTW, I'm curious, did you also notice your home assistant working better with this PR?
I only discovered this when my vacuum broke (fixed now), that it was working awfully. I wonder if you also had bad performance for months because of this

**Comment by dbuezas** [comment]
Ok, If it is not connected, HA won't send the play command. I guess it used to work because the send command would error.

**Comment by dbuezas** [comment]
Do you know why the update function has an ` or self._volume is not None` ?
I don't understand that part

**Comment by dbuezas** [comment]
Should be fixed now

**Comment by definitio** [comment]
> BTW, I'm curious, did you also notice your home assistant working better with this PR? 

It's definitely better now.

> Do you know why the update function has an `or self._volume is not None` ?

The first version of [sound server](https://github.com/zvldz/vacuum/commits/master/custom-script/files/sound_server/sound_server.pl) doesn't support volume control and state reporting. I used `self._volume` to detect version of server. There was some compatibility problems between old and new versions. It was 3 years ago, I don't remember how exactly that works. Probably nobody uses old version now and this hack can be removed.

**Pull request merged**
